name: Sync Velog Posts

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 14 * * *' # 한국 시간(KST) 23:00는 UTC 14:00
  workflow_dispatch: # 수동으로도 실행 가능하게 설정

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 깃허브에 커밋할 수 있는 권한 부여

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests feedparser

      - name: Run script
        run: python update_velog.py

      - name: Commit and Push
        run: |
          # 1. 사용자 정보 설정 (이 부분이 본인 계정이어야 잔디가 심어집니다)
          git config --local user.email "rladmstjs120@gmail.com"
          git config --local user.name "agline"
          
          # 2. 변경된 파일 추가
          git add .
          
          # 3. 변경사항이 있을 때만 커밋
          if ! git diff --staged --quiet; then
            git commit -m "Update Velog posts"
            git push
          fi
